Command line
rohithasrk/GSoC-Organisation-Scraper pull request #22
Opened 2017-12-21 21:51 UTC by ashuparija

This branch adds the feature of giving the file name as a command line argument so as to store the output of the program in that file.

2017-12-21 22:37 UTC, rohithasrk commented
@ashuparija I kind of feel there is an easy way here. Why not take the technology as input in the arguments? Like `python scrape.py python`

2017-12-21 22:38 UTC, rohithasrk commented
Outputting to file just needs a pipe when this is done. `python scrape.py python > file_name.txt`

2017-12-22 12:01 UTC, ashuparija commented
@rohithasrk Yes, i see your point of view and I agree that the technology as input in the arguments will be better. I will try to that instead.

2017-12-23 07:08 UTC, ashuparija commented
@rohithasrk I've updated the branch. Can you please review.

2017-12-23 12:51 UTC, rohithasrk requested changes
Hey @ashuparija. Good job with it. There are some small style changes I'd like to suggest. Please check the inline comments for same. You can use flake8 to check these style errors. There are some incorrect tabs/ spaces errors too. Which would be a problem with > python3.

Also, squash all the commits and add a commit message like `Enable search using sys arguments`

2017-12-23 12:51 UTC, rohithasrk commented on scrape.py
>          "Enter a technology of preference: " +
Incorrect indentation. Please indent towards right.

2017-12-23 12:51 UTC, rohithasrk commented on scrape.py
> +
Remove the above blank lines(3)

2017-12-23 12:51 UTC, rohithasrk commented on scrape.py
> +
Blank line not needed

2017-12-23 17:27 UTC, ashuparija commented
@rohithasrk I have updated using the changes suggested. Can you please review.

2017-12-24 04:32 UTC, rohithasrk commented
@ashuparija There seems to be some conflict arising. Can you check it out once? :D

2018-02-01 19:58 UTC, merged